### ISSUE TITLE
Additional events in webhooks

### ISSUE THREAD

**Issue by ndeet** [btcpayserver/xenforo#1]
Hi! First of all, thank you very much for building this great integration for BTCPay Server :hugs: 

On processing the webhooks it only listenens to the InvoiceSettled event at the moment which means that a few cases are not covered

- it will only process if the payment settled normally
- this means after transaction confirmed in a block which can take a few to 30+ minutes worst case (for on-chain transactions)
- late payments not covered (expired invoices can be paid)
- partial payments not covered (could have some note that it was partially paid)
- expired invoices

Not sure if XF has some concept of order states so maybe not all usecases can or should be covered but you can see in our WooCommerce plugin [how to cover all cases](https://github.com/btcpayserver/woocommerce-greenfield-plugin/blob/master/src/Gateway/AbstractGateway.php#L501)

You likely would not need all of it but I would at least additionally cover the case of an expired invoice paid late, which will not fire `InvoiceSettled` but rather a `InvoiceExpired` followed by an `InvoicePaymentSettled` 

Let me know if you have any questions. 

Thank you.

**Comment by 021-projects** [comment]
https://github.com/btcpayserver/xenforo/commit/8443ff5ba9138982b53c4d24b2baeae9dfe79d88
