### ISSUE TITLE
Version 2.0.0 Invoice Alert fail

### ISSUE THREAD

**Issue by BenjaminM007** [btcpayserver/xenforo#11]
When we updated to version 2.0.0 and if we enable invoice alerts we receive the error below. If we disable the invoice alerts everything works as expected.

We are using BTCPay Server v1.13.5+30d91d0bd

`LogicException: Could not find repository 'XF\Repository\UserAlertRepository' for 'XF\Repository\UserAlertRepository' in src/XF/Mvc/Entity/Manager.php at line 260
1. XF\Mvc\Entity\Manager->getRepository() in src/XF/App.php at line 2910
2. XF\App->repository() in src/XF.php at line 890
3. XF::repository() in src/addons/BS/BtcPayProvider/Payment/BTCPayServer.php at line 62
4. BS\BtcPayProvider\Payment\BTCPayServer->sendAlertWithInvoice() in src/addons/BS/BtcPayProvider/Payment/BTCPayServer.php at line 44
5. BS\BtcPayProvider\Payment\BTCPayServer->initiatePayment() in src/XF/Pub/Controller/Purchase.php at line 30
6. XF\Pub\Controller\Purchase->actionIndex() in src/XF/Mvc/Dispatcher.php at line 352
7. XF\Mvc\Dispatcher->dispatchClass() in src/XF/Mvc/Dispatcher.php at line 259
8. XF\Mvc\Dispatcher->dispatchFromMatch() in src/XF/Mvc/Dispatcher.php at line 115
9. XF\Mvc\Dispatcher->dispatchLoop() in src/XF/Mvc/Dispatcher.php at line 57
10. XF\Mvc\Dispatcher->run() in src/XF/App.php at line 2485
11. XF\App->run() in src/XF.php at line 524
12. XF::runApp() in index.php at line 20`

**Comment by 021-projects** [comment]
Hello!
It seems you installed the XenForo 2.3 version on XenForo 2.2. For XenForo 2.2 you should use version 1.1.0

**Comment by BenjaminM007** [comment]
Thank you very much. That was the issue.
