### ISSUE TITLE
Cannot complete payment without being administrator

### ISSUE THREAD

**Issue by benmcguire79** [btcpayserver/xenforo#5]
Attempting to make a payment as a normal registered Xenforo user the payment screen never appears, however when an administrator attempts this the payment box appears and I can complete the payment.

When a normal user tries to make a payment an invoice is generated on the BTC server but the user never sees the payment box so they cannot make a payment.

Is there some hidden code that only allows administrators to make payments ?

**Comment by 021-projects** [comment]
Hello! 

No, payments should work for all users. What add-ons do you have installed?

**Comment by benmcguire79** [comment]
![Screenshot from 2024-05-15 17-49-01](https://github.com/btcpayserver/xenforo/assets/19871799/69168281-7a95-46a8-b169-f99c7bd434f6)
![Screenshot from 2024-05-15 17-49-16](https://github.com/btcpayserver/xenforo/assets/19871799/3ef50f50-d666-4a7e-bf7f-8303c676476c)
![Screenshot from 2024-05-15 17-49-45](https://github.com/btcpayserver/xenforo/assets/19871799/1be4b311-0475-4879-9589-8079e6c90c1f)
![Screenshot from 2024-05-15 17-49-56](https://github.com/btcpayserver/xenforo/assets/19871799/7de86634-419b-44c5-8605-d4bf1f334d06)
![Screenshot from 2024-05-15 17-50-12](https://github.com/btcpayserver/xenforo/assets/19871799/198848fa-1115-42ca-ac4f-57bf8dcc38fb)


There are the addons. Again I as an admin can make payments with no issue but a normal user can generate an invoice which I see on the BTC server but the popup payment box never appears.
Very strange.

**Comment by sacommscc** [comment]
Please choose a valid payment profile to continue with your purchase.  but it was working fine when i started now its not for user upgrade

**Comment by 021-projects** [comment]
> Please choose a valid payment profile to continue with your purchase. but it was working fine when i started now its not for user upgrade

Hello! Could you please post the settings for the upgrade you can't purchase but which used to work?
