### ISSUE TITLE
Xenforo 2.3.2

### ISSUE THREAD

**Issue by nuh03** [btcpayserver/xenforo#9]
Is it updated for xenforo 2.3.2 becuz it doesnt work on my forums when i click on payment nothing happend

**Comment by 021-projects** [comment]
Hello! 

No, this add-on is not currently adapted for XF 2.3. Unfortunately, I will be able to resolve this issue only in the fall. I will be grateful for your waiting 🙏😌

**Comment by nuh03** [comment]
Any updates ?

**Comment by 021-projects** [comment]
https://github.com/btcpayserver/xenforo/releases/tag/v2.0.0
